services:
  items_db:
    container_name: postgres-database
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=items_db
    ports:
      - '5432:5432'
