# Generated by Django 5.2.4 on 2025-07-31 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTovar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_prep', models.CharField(max_length=255)),
                ('ean13', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_prep', models.CharField(max_length=255)),
                ('ean13', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MatchedTovar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('client_tovars', models.ManyToManyField(to='items.clienttovar')),
                ('tovar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.tovar')),
            ],
        ),
    ]
